Repository team-Ollie/wecare-server, pull requests merged in 2024-06, with the labels that each got.

#5 #1 feat: 프로젝트 초기 설정
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/ollie/wecare/WecareApplication.java
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/PostChallengeReq.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/entity/ChallengeAttendance.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/common/Base/BaseEntity.java
  src/main/java/ollie/wecare/common/Base/BaseException.java
  src/main/java/ollie/wecare/common/Base/BaseExceptionHandler.java
  src/main/java/ollie/wecare/common/Base/BaseResponse.java
  src/main/java/ollie/wecare/common/Base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/enums/Role.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/entity/Program.java
  src/main/java/ollie/wecare/program/entity/Tag.java
  src/main/java/ollie/wecare/program/repository/ProgramRepository.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/UpdateUserReq.java
  src/main/java/ollie/wecare/user/entity/Center.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/UserService.java
  src/test/java/ollie/wecare/WecareApplicationTests.java
Labels: ✨ feature

#6 [feature/1-setting] Entity Annotation 추가
  src/main/java/ollie/wecare/challenge/entity/ChallengeAttendance.java
Labels: ⚙ infra

#11 [feature/1-projectSetting] Exception 처리를 위한 GlobalExceptionHandler 정의
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/entity/ChallengeAttendance.java
  src/main/java/ollie/wecare/common/Base/BaseExceptionHandler.java
  src/main/java/ollie/wecare/common/Base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/base/BaseEntity.java
  src/main/java/ollie/wecare/common/base/BaseException.java
  src/main/java/ollie/wecare/common/base/BaseResponse.java
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/exception/ErrorResponse.java
  src/main/java/ollie/wecare/common/exception/GlobalExceptionHandler.java
  src/main/java/ollie/wecare/program/entity/Program.java
  src/main/java/ollie/wecare/program/entity/Tag.java
  src/main/java/ollie/wecare/user/entity/Center.java
  src/main/java/ollie/wecare/user/entity/User.java
Labels: ✨ feature

#12 [feature/1-projectSetting] RequestURI 파일 분리 및 누락된 dependency 추가
  build.gradle
  src/main/java/ollie/wecare/common/constants/RequestURI.java
Labels: ✨ feature, 🛠 fix

#13 [feature/10-signup] 회원가입 API
  src/main/java/ollie/wecare/common/base/BaseEntity.java
  src/main/java/ollie/wecare/common/base/BaseException.java
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/constants/Constants.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/JwtDto.java
  src/main/java/ollie/wecare/user/dto/SignupRequest.java
  src/main/java/ollie/wecare/user/dto/UpdateUserReq.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/repository/CenterRepository.java
  src/main/java/ollie/wecare/user/service/AuthService.java
  src/main/java/ollie/wecare/user/service/RedisService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature, 🛠 fix

#14 [feature/10-logout] 로그인, 로그아웃 API
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/configuration/AppConfiguration.java
  src/main/java/ollie/wecare/common/configuration/RedisConfiguration.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/LoginRequest.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/AuthService.java
  src/main/java/ollie/wecare/user/service/RedisService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#15 [feature/10-signout] 회원탈퇴 API
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/SignOutRequest.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/service/AuthService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#16 [feature/10-reissueToken] 토큰 재발급 API
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/ReissueTokenRequest.java
  src/main/java/ollie/wecare/user/dto/TokenResponse.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/RedisService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#17 [feature/10-validateNickname] 닉네임 중복체크 API
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/NicknameRequest.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#18 [feature/10-validateLoginId] 아이디 중복 체크 API 구현
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/LoginIdRequest.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#19 [feature/10-editNickname] 닉네임 변경 API
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/EditNicknameRequest.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#20 [feature/10-editPassword] 비밀번호 변경 API
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/EditPasswordRequest.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#21 [feature/10-getMyPage] 마이페이지 조회 API
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/MyPageResponse.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#22 [feature/10-getSignupView] 회원가입 화면 조회 API
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/CenterListDto.java
  src/main/java/ollie/wecare/user/dto/SignupViewResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature

#26 [feature/25-docker] 배포 자동화를 위한 Dockerfile 생성
  Dockerfile
Labels: 🐳 CI/CD

#29 [feature/27-jwt] Jwt 관련 Filter 및 Configuration 구현
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
  src/main/java/ollie/wecare/common/jwt/JwtAuthenticationFilter.java
  src/main/java/ollie/wecare/common/jwt/JwtExceptionFilter.java
  src/main/java/ollie/wecare/user/repository/UserRepository.java
  src/main/java/ollie/wecare/user/service/AuthService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: ✨ feature, 🗂️ config

#30 [config/28-cors] WebConfiguration 설정
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
Labels: 🗂️ config

#31 [config/28-cors] WebSecurityConfiguration에서 cors 설정 구현
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🗂️ config

#33 #32 config: Redis 설정
  src/main/java/ollie/wecare/common/configuration/RedisConfiguration.java
Labels: 🗂️ config

#24 [feature/3-postProgram] 프로그램 등록 API 구현
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/GetProgramRes.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: ✨ feature

#36 [feature/3-getPrograms] 프로그램 조회 (월별)
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/GetProgramRes.java
  src/main/java/ollie/wecare/program/repository/ProgramRepository.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: ✨ feature

#37 [feat/4-getChallengeAds] 챌린지 광고 조회 API 구현
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdsRes.java
  src/main/java/ollie/wecare/challenge/dto/PostChallengeReq.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature

#38 [fix/10-editPassword] 비밀번호 변경시 암호화 추가
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#39 [chore/10-updateEnumType] User entity enumType 변경
  src/main/java/ollie/wecare/user/entity/User.java
Labels: 🧹 chore

#40 [develop] main merge
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceRes.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdsRes.java
  src/main/java/ollie/wecare/challenge/dto/PostChallengeReq.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/GetProgramRes.java
  src/main/java/ollie/wecare/program/repository/ProgramRepository.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/entity/User.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#41 [feature/28-cors] Allowedorigins 추가
  .github/workflows/build.yml
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🗂️ config

#42 [develop] allowedorigins 추가
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🐳 CI/CD

#43 [fix/28-cors] allowedorigins에 프론트 배포 url 추가
  README.md
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🛠 fix

#44 [develop] cors 설정을 위한 프론트 url 추가
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🐳 CI/CD

#46 [fix/45-getMypage] 마이페이지 조회 시 관리자 여부, 로그인 아이디 추가 반환하도록 수정
  src/main/java/ollie/wecare/user/dto/MyPageResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#47 [develop] 마이페이지 조회 수정 반영
  src/main/java/ollie/wecare/user/dto/MyPageResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#48 [fix/signUp] 회원가입 시 중복 아이디 예외처리 추가
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#49 #4 fix: 챌린지 광고 기준 변경
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdsRes.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
Labels: ✨ feature, 🛠 fix

#52 [fix/51-getPrograms] 프로그램 월별 조회 API 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/common/constants/RequestURI.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🛠 fix

#56 [fix/55-login] 로그인 반환값 수정
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/LoginResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#57 [fix/51-getPrograms] 프로그램 마감일자 반환 형식 변경
  src/main/java/ollie/wecare/program/dto/DateDto.java
  src/main/java/ollie/wecare/program/dto/GetProgramRes.java
Labels: 🛠 fix

#53 [develop] 프로그램 월별 조회 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/common/constants/RequestURI.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/DateDto.java
  src/main/java/ollie/wecare/program/dto/GetProgramRes.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/controller/UserController.java
  src/main/java/ollie/wecare/user/dto/LoginResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#58 [fix/nicknameValidation] 닉네임 validation 추가
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#59 [develop] 닉네임 validation 추가
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#63 #60 fix: 챌린지 검색 API 파라미터 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
Labels: 🛠 fix

#68 [develop] 챌린지 월별 조회 API 수정
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceRes.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix, 🐳 CI/CD

#69 [fix/28-cors] allowedOrigins에서 불필요한 url 삭제
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🛠 fix

#70 [develop] main merge
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🐳 CI/CD

#71 [fix/28-cors] allowedOrigins에 배포 url 추가 수정
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🛠 fix

#72 [develop] allowedOrigins 추가 수정
  src/main/java/ollie/wecare/common/configuration/WebConfiguration.java
  src/main/java/ollie/wecare/common/configuration/WebSecurityConfiguration.java
Labels: 🐳 CI/CD

#75 [fix/60-searchChallenge2] REVERT 챌린지 검색시 참여 중인 챌린지 제외
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#76 [fix/validUser] 비회원 예외처리 메서드 추가
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#77 [develop] 비회원 예외처리 추가
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#78 [fix/60-searchChallenge] 챌린지 검색시 이미 참여 중인 챌린지 제외
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#79 [develop] 챌린지 검색 API 이미 참여 중인 챌린지 제외
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#81 [feature/4-getAttendanceCode] 챌린지 인증코드 발급 API 구현
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceCodeReq.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature

#82 [develop] 챌린지 인증코드 발급 API 구현
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceCodeReq.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#80 [feature/4-getAttendanceCode] 챌린지 인증코드 발급 API 구현
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceCodeReq.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature
