Repository team-Ollie/wecare-server, pull requests merged in 2024-07, with the labels that each got.

#85 [feature/84-tag] TagEnum 정의 및 Tag entity 수정
  README.md
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/enums/TagEnum.java
  src/main/java/ollie/wecare/program/entity/Tag.java
Labels: ✨ feature, 🛠 fix

#86 [feature/83-getPrograms] 프로그램 전체 목록 조회 API
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/ProgramListResponse.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: ✨ feature

#87 [fix/84-tag] 프로그램과 태그 관계 설정 메서드 추가
  src/main/java/ollie/wecare/program/entity/Program.java
  src/main/java/ollie/wecare/program/entity/Tag.java
Labels: 🛠 fix

#88 [develop] Tag 관련 enum 정의 및 프로그램 목록 조회 구현
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/common/enums/TagEnum.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/ProgramListResponse.java
  src/main/java/ollie/wecare/program/entity/Program.java
  src/main/java/ollie/wecare/program/entity/Tag.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🐳 CI/CD

#90 [fix/89-getChallengeDetail] 챌린지 상세 조회 로직 구현
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/ChallengeDetailResponse.java
  src/main/java/ollie/wecare/challenge/dto/GetAttendanceRes.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengesRes.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/entity/ChallengeAttendance.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/common/base/BaseResponseStatus.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🛠 fix

#91 [fix/60-searchChallenge] 챌린지 검색 API 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeAttendanceRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/dto/ProgramListResponse.java
  src/main/java/ollie/wecare/program/entity/Program.java
  src/main/java/ollie/wecare/program/entity/Tag.java
  src/main/java/ollie/wecare/program/repository/TagRepository.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#96 [feature/4-participateChallenge] 새로운 챌린지 참여시 participants 추가
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature

#97 [fix/61-getChallengeAds] 챌린지 광고 API dto 변경
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdRes.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdsRes.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#98 [develop] 새로운 챌린지 참여시 participants 추가, 챌린지 광고 API dto 변경
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdRes.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdsRes.java
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#99 [fix/60-getChallenges] 챌린지 조회시 참여 중인 챌린지 제외
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#100 [feature/3-saveProgram] 프로그램 등록시 챌린지 등록
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: ✨ feature

#101 [fix/73-calculateAttendanceRate] 챌린지 달성률 계산
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🛠 fix

#102 [develop] 챌린지 조회시 참여 중인 챌린지 제외, 프로그램 등록시 챌린지 등록, 챌린지 달성률 계산
  src/main/java/ollie/wecare/challenge/entity/Challenge.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🐳 CI/CD

#103 [feature/4-getMyChallengesAdmin] 관리자 챌린지 목록 조회 API
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengesAdminRes.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature

#104 [feature/4-getMyChallengesAdmin] 관리자 챌린지 현황 조회 API
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdminRes.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: ✨ feature

#105 [develop] 관리자 챌린지 조회 API
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengeAdminRes.java
  src/main/java/ollie/wecare/challenge/dto/GetChallengesAdminRes.java
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#107 [fix/106-login] 로그인 response centerIdx 추가
  src/main/java/ollie/wecare/user/dto/LoginResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#110 [fix/login] 로그인 응답에 centerIdx를 centerName으로 변경
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/dto/LoginResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🛠 fix

#111 [develop] 로그인 응답 형태 변경
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
  src/main/java/ollie/wecare/user/dto/LoginResponse.java
  src/main/java/ollie/wecare/user/service/UserService.java
Labels: 🐳 CI/CD

#112 [fix/searchChallenge] 챌린지 검색 시 빈 문자열 요청이 들어올 경우 전체 목록을 반환하도록 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#113 [develop] 챌린지 검색 반환값 수정
  src/main/java/ollie/wecare/challenge/controller/ChallengeController.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#114 [fix/searchChallenge] 챌린지 검색 시 참여중인 챌린지는 제외하고 보내도록 수정
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#115 [develop] 챌린지 검색 시 참여중인 챌린지는 제외하도록 수정
  src/main/java/ollie/wecare/challenge/repository/ChallengeRepository.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#116 [fix/getChallenges] 챌린지 목록 조회 시 태그 제외
  src/main/java/ollie/wecare/challenge/dto/GetChallengesRes.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🛠 fix

#117 [develop] 챌린지 목록 조회 시 태그 제외하도록 수정
  src/main/java/ollie/wecare/challenge/dto/GetChallengesRes.java
  src/main/java/ollie/wecare/challenge/service/ChallengeService.java
Labels: 🐳 CI/CD

#118 [fix/signupView] 센터 목록 조회 오타 수정
  src/main/java/ollie/wecare/user/dto/SignupViewResponse.java
Labels: 🛠 fix

#119 [develop] master merge
  src/main/java/ollie/wecare/user/dto/SignupViewResponse.java
Labels: 🐳 CI/CD

#121 [fix/120-saveProgram] 프로그램 등록 시 연쇄적으로 태그, 챌린지를 생성하도록 수정
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🛠 fix

#122 [develop] 프로그램 등록 로직 개선
  src/main/java/ollie/wecare/program/controller/ProgramController.java
  src/main/java/ollie/wecare/program/dto/PostProgramReq.java
  src/main/java/ollie/wecare/program/service/ProgramService.java
Labels: 🐳 CI/CD
